version: "3.8"

services:     
  cache:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6379:6379'
  
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_DB=pm-db-local
      - POSTGRES_USER=preference-manager
      - POSTGRES_PASSWORD=preference-manager-pass
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./scripts/create_pm_db.sql:/docker-entrypoint-initdb.d/create_pm_db.sql